# Generated by Django 4.0.3 on 2022-03-19 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_beat_options_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
