# Generated by Django 4.0.3 on 2022-03-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_beat_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beat',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
