# Generated by Django 4.0.3 on 2022-03-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_beat_options_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
