# Generated by Django 4.0.3 on 2022-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_beat_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
