# Generated by Django 4.0.3 on 2022-04-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
